# Generated by Django 2.2.5 on 2020-01-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descripction',
            new_name='description',
        ),
    ]
