# Generated by Django 2.2.5 on 2020-01-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200127_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descripction_html',
            new_name='description_html',
        ),
    ]
